### ISSUE TITLE
Make bootstrap recipe fails trying to write to an existing directory

### ISSUE THREAD

**Issue by ross-spencer** [artefactual-labs/am#30] opened 2017-12-15 04:38 UTC
Error occurs when trying to reset the environment once it has been deployed, e.g. for testing. 

```
INFO      2017-12-14 20:16:25  common.models:models:create_testuser:18:  Creating test user -- login: test, password: test
docker-compose run \
	--rm \
	--entrypoint /src/storage_service/manage.py \
		archivematica-storage-service \
			create_user \
				--username="test" \
				--password="test" \
				--email="test@test.com" \
				--api-key="test"
Starting compose_mysql_1 ... done
User found.
User updated.
API key updated.
docker-compose exec --user root archivematica-storage-service \
	git clone https://github.com/artefactual/archivematica-sampledata.git \
	/home/archivematica/archivematica-sampledata
fatal: destination path '/home/archivematica/archivematica-sampledata' already exists and is not an empty directory.
Makefile:24: recipe for target 'bootstrap-storage-service' failed
make: *** [bootstrap-storage-service] Error 128
```

The result is a dashboard/pipeline error, that seems to prevent us from accessing our external volumes.

```
archivematica-dashboard_1        | WARNING   2017-12-15 04:19:54  archivematica.common:storageService:_get_pipeline:122:  This Archivematica instance is not registered with the storage service or has been disabled.
archivematica-dashboard_1        | WARNING   2017-12-15 04:19:54  archivematica.common:storageService:_get_pipeline:125:  Error fetching pipeline
archivematica-dashboard_1        | Traceback (most recent call last):
archivematica-dashboard_1        |   File "/src/archivematicaCommon/lib/storageService.py", line 123, in _get_pipeline
archivematica-dashboard_1        |     response.raise_for_status()
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
archivematica-dashboard_1        |     raise HTTPError(http_error_msg, response=self)
archivematica-dashboard_1        | HTTPError: 404 Client Error: NOT FOUND for url: http://archivematica-storage-service:8000/api/v2/pipeline/f6e986db-9cdf-4951-a05b-d621d62c6264/
archivematica-dashboard_1        | ERROR     2017-12-15 04:19:54  archivematica.dashboard:views:transfer_source_locations:59:  Error retrieving source directories
archivematica-dashboard_1        | Traceback (most recent call last):
archivematica-dashboard_1        |   File "/src/dashboard/src/components/transfer/views.py", line 56, in transfer_source_locations
archivematica-dashboard_1        |     return helpers.json_response(storage_service.get_location(purpose="TS"))
archivematica-dashboard_1        |   File "/src/archivematicaCommon/lib/storageService.py", line 149, in get_location
archivematica-dashboard_1        |     pipeline = _get_pipeline(get_setting('dashboard_uuid'))
archivematica-dashboard_1        |   File "/src/archivematicaCommon/lib/storageService.py", line 123, in _get_pipeline
archivematica-dashboard_1        |     response.raise_for_status()
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
archivematica-dashboard_1        |     raise HTTPError(http_error_msg, response=self)
archivematica-dashboard_1        | HTTPError: 404 Client Error: NOT FOUND for url: http://archivematica-storage-service:8000/api/v2/pipeline/f6e986db-9cdf-4951-a05b-d621d62c6264/
```

**Comment by sevein** [comment] 2017-12-15 14:05
Duplicate of #15?

**Comment by sevein** [comment] 2017-12-15 14:23
@ross-spencer I think I did a poor job describing the issue #15, i.e. named the issue after the solution not the actual problem that's why I guess you couldn't find it! I'm going to close this and update the title of #15.

**Closed by sevein** 2017-12-15 14:23 UTC
