### ISSUE TITLE
Problem: make bootstrap-dashboard-frontend fails with file not found 

### ISSUE THREAD

**Issue by helrond** [artefactual-labs/am#69] opened 2018-08-29 17:22 UTC
While running `make bootstrap` I encountered the following error:

```
npm ERR! path /src/dashboard/frontend/appraisal-tab/node_modules/http-server/bin/http-server
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/src/dashboard/frontend/appraisal-tab/node_modules/http-server/bin/http-server'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-29T16_39_33_357Z-debug.log
make: *** [bootstrap-dashboard-frontend] Error 254
```
I resolved this by adding `"imports-loader": "^0.6.5",` to the `devDependencies` in `am/src/archivematica/src/dashboard/frontend/appraisal-tab/package.json`

I'm on macOS High Sierra, Docker version 18.06.0-ce, docker-compose version 1.22.0

This **may** be related to #49

**Comment by sevein** [comment] 2018-08-29 19:01
Hi @helrond, thanks for the report. We haven't figured this out yet. @ablwr recently added a comment to the README file warning users about the permission issues with Docker for Mac and also this section in the troubleshooting guide: https://github.com/artefactual-labs/am/tree/master/compose#make-bootstrap-fails-to-run.

I don't think I understand yet what's the root cause, but definitely related to the shared volumes and running `bootstrap-dashboard-frontend` when the volumes are mounted. Not reproducible when the host runs Linux though.

https://github.com/artefactual/archivematica/pull/1241 may mitigate the issues when the image build fails (i.e. `docker-compose build archivematica-dashboard`), so that's something we could try at some point. But that won't fix the problem with `bootstrap-dashboard-fronted`. One option is to write a script that build the assets inside the container but in a different location that isn't under a shared volume and then copy the assets manually, but it'd be pretty ugly. I wish I knew better what was going, didn't have a lot of time to investigate.

In the meantime, you can disable "bootstrap-dashboard-frontend" or make it a no-op and build the assets locally. I usually do that with `yarn install`, it's pretty fast. @ablwr also mentioned this solution here: https://github.com/artefactual-labs/am/issues/49#issuecomment-417038824.

**Comment by helrond** [comment] 2018-08-29 19:45
Thanks @seveinm, I appreciate the followup! I followed @ablwr's instructions for building assets locally I was able to get it all to work.

**Comment by sevein** [comment] 2018-09-29 17:04
Replaced by https://github.com/archivematica/Issues/issues/226.

**Closed by sevein** 2018-09-29 17:04 UTC
